// Wizard UI copy (vi + en). English is a first draft — wording to be polished later.
// Quiz option labels are NOT here: they reuse the existing `<field>_tier_<value>`
// keys in ../i18n so the stored English tier codes and their labels stay in one place.

const vi = {
  appName: 'StudyLink',
  langToggle: 'Đổi ngôn ngữ',
  idLabel: 'ID',
  saved: 'Đã lưu thay đổi',
  saving: 'Đang lưu…',
  saveError: 'Lỗi lưu — thử lại',
  home: 'Trang chủ',
  loading: 'Đang tải…',
  splashHint: 'Chạm để tiếp tục',
  signOut: 'Đăng xuất',
  provMajor: 'Thành phố lớn',
  provOther: 'Tỉnh / thành khác',
  serviceUpdating: 'Hệ thống đang được cập nhật. Vui lòng thử lại sau ít phút.',

  // Register
  regHaveAccount: 'Đã có tài khoản StudyLink?',
  regLogin: 'Đăng nhập',
  regLoginHere: 'tại đây',
  regTitle: 'Đăng ký',
  fullName: 'Họ và tên',
  fullNamePh: 'Nhập họ và tên',
  phone: 'Số điện thoại',
  phonePh: '098 1234567',
  email: 'Địa chỉ email',
  emailPh: 'email@example.com',
  yob: 'Năm sinh',
  yobPh: 'Ví dụ: 1998',
  channel: 'Bạn biết StudyLink từ kênh truyền thông',
  channelSource: 'Nguồn',
  referrerName: 'Tên người giới thiệu',
  optional: 'Không bắt buộc',
  event: 'Bạn biết StudyLink qua sự kiện',
  eventNone: 'Không qua sự kiện',
  eventLocked: 'Bạn đăng ký qua sự kiện — kênh truyền thông đã được ghi nhận.',
  residence: 'Nơi cư trú',
  dream: 'Ước mơ Du Học',
  choose: 'Chọn',
  connect: 'Bạn muốn kết nối với StudyLink?',
  yes: 'Có',
  no: 'Không',
  consent: 'Khi bấm “Bắt đầu phiêu lưu”, bạn đồng ý để StudyLink lưu trữ và sử dụng thông tin của bạn nhằm tư vấn du học. Nếu bạn dưới 18 tuổi, vui lòng có sự đồng ý của phụ huynh.',
  start: 'Bắt đầu phiêu lưu',
  checking: 'Đang kiểm tra…',
  connecting: 'Đang kết nối…',
  errRequired: 'Vui lòng điền đầy đủ các mục bắt buộc.',
  errEmail: 'Email chưa đúng định dạng.',
  errYob: 'Năm sinh phải từ 1980 đến 2018.',
  errGeneric: 'Có lỗi xảy ra. Vui lòng thử lại.',
  welcomeBack: 'Chào mừng bạn trở lại',
  welcomeBackActive: 'Bạn đã có một hồ sơ đang hoạt động với chúng tôi. Chúng tôi sẽ đưa bạn đến đó để xem và cập nhật thông tin.',
  welcomeBackNew: 'Bạn đã đăng ký với chúng tôi. Một hồ sơ mới sẽ được tạo cho bạn.',
  continue: 'Tiếp tục',
  createEnquiry: 'Tạo hồ sơ mới',
  cancel: 'Huỷ',
  conflictTitle: 'Chúng tôi tìm thấy nhiều hồ sơ',
  conflictHint: 'Chọn hồ sơ của bạn. Các hồ sơ còn lại sẽ được ngừng sử dụng.',
  keepSelected: 'Giữ hồ sơ đã chọn',

  // Hub
  hello: 'Xin chào bạn ! 👋',
  hubLead1: 'Hãy bắt đầu hành trình ',
  hubLeadHl: 'Giải Mã Chỉ Số Xuất Ngoại',
  hubLead2: ' của bạn nào!',
  thanks1: ' xin cảm ơn bạn… đã cung cấp thông tin liên hệ cần thiết.',
  bubble1: "Cùng xem 'chân dung' của bạn có gì thú vị nhé!",
  bubble2: 'Cố lên nào! Sắp đến bước cuối cùng rồi.',
  bubble3: 'Ngành nghề nào sẽ phù hợp với bạn trong tương lai? Cùng khám phá tiếp nào!',
  step1Title: 'CHÂN DUNG BẢN MỆNH',
  step1Desc: 'Phác họa chân dung bản mệnh của bạn.',
  step2Title: 'CHỈ SỐ XUẤT NGOẠI',
  step2Desc: 'Khám phá vận mệnh xuất ngoại của bạn.',
  step3Title: 'TIÊN ĐOÁN NGHỀ NGHIỆP',
  step3Desc: 'Định hướng ngành nghề phù hợp với bạn.',
  letsGo: 'Bắt đầu thôi',
  stepDone: 'Đã hoàn thành',
  gift1: 'Hoàn thành hành trình để nhận một món quà ',
  giftHl: '"KU-TE"',
  gift2: ' từ StudyLink nhé! 🎁',
  comingSoon: 'Bước này đang được hoàn thiện. Vui lòng quay lại sau.',

  // Step 1 — Chân dung bản mệnh
  next: 'Tiếp Tục',
  s1Title: 'CHÂN DUNG BẢN MỆNH',
  parent: 'Phụ huynh',
  parentPick: 'Chọn: Mẹ / Ba',
  mother: 'Mẹ',
  father: 'Ba',
  parentName: 'Họ và tên',
  parentPhone: 'Điện thoại',
  parentEmail: 'Email',
  countries: 'Quốc gia yêu thích',
  countriesHint: '(Bấm chọn quốc gia)',
  countriesCount: 'Đã chọn {n}/3 quốc gia',
  timeline: 'Thời gian dự kiến xuất ngoại',
  timelinePick: 'Chọn thời gian',
  socialTitle: 'Mạng xã hội (không bắt buộc)',
  socialPlatform: 'Nền tảng',
  socialHandle: 'Tên tài khoản hoặc đường dẫn',
  socialNone: 'Không chọn',
  errParent: 'Vui lòng chọn phụ huynh.',
  errParentName: 'Vui lòng nhập họ tên phụ huynh.',
  errParentPhone: 'Vui lòng nhập số điện thoại phụ huynh.',
  errParentEmail: 'Email phụ huynh chưa đúng định dạng.',
  errCountries: 'Vui lòng chọn ít nhất 1 quốc gia.',
  saveFailed: 'Không lưu được. Vui lòng thử lại.',

  // Step 2 — Chỉ số xuất ngoại
  s2Title: 'XEM CHỈ SỐ',
  s2Sub1: 'Hoàn thành bảng ',
  s2SubB: '9 câu hỏi',
  s2Sub2: ' để tính chỉ số',
  calcIndex: 'Tính chỉ Số Xuất Ngoại',
  calculating: 'Đang tính…',
  quizIncomplete: 'Còn {n} câu chưa trả lời.',
  questionOf: 'Câu {n}/{total}',
  retakeGem: 'Làm lại bài Giải Mã',
  gemTitle: 'Viên Bản Thạch Xuất Ngoại của Bạn',
  step1First: 'Hoàn thành “Chân dung bản mệnh” trước để chỉ số chính xác hơn.',
  goStep1: 'Đến Chân dung bản mệnh',

  // Step 3 — Tiên đoán nghề nghiệp
  s3Title: 'SỰ NGHIỆP TƯƠNG LAI',
  s3Sub1: 'Hoàn thành bảng ',
  s3SubB: '15 câu hỏi',
  s3Sub2: ' để tính chỉ số',
  predict: 'Dự đoán Nghề',
  retakeCareer: 'Làm lại bài Tiên Đoán Nghề',
  finish: 'Hoàn thành',
  careerNeedsStep1: 'Hãy hoàn thành “Chân dung bản mệnh” (thông tin phụ huynh và quốc gia) để mở khóa kết quả cuối cùng.',
  scoreLabel: 'Điểm',

  // Congrats + share + contact
  cheer1: 'Hoo…',
  congrats: 'Chúc mừng Bạn',
  unlocked: 'đã mở khóa',
  unlockedTitle1: 'CHỈ SỐ XUẤT NGOẠI và',
  unlockedTitle2: 'DỰ ĐOÁN CÔNG DANH',
  prize1: 'Bản đồ Chỉ Số Xuất Ngoại của Bạn đã được giải mã thành công! Cùng với lộ trình bứt phá tương lai, Bạn nhận ngay cơ hội lái ',
  prizeHl: 'chiếc xe máy điện VinFast cực xịn về nhà',
  prize2: ' như một món quà xuất phát điểm dành riêng cho Bạn.',
  shareBtn: 'Chia sẻ kết quả với Chuyên gia StudyLink',
  roadmap: 'Nhận lộ trình xuất ngoại MIỄN PHÍ',
  shareTitle1: 'Bạn muốn chia sẻ ',
  shareTitleHl: 'Bản Mệnh Xuất Ngoại',
  shareTitle2: ' qua:',
  shareText: 'Khám phá bản thân, mở lối tương lai cùng StudyLink!',
  shareCopy: 'Sao chép đường link',
  shareCopied: 'Đã sao chép!',
  shareCopiedHint: 'Đã sao chép liên kết — hãy dán vào ứng dụng bạn muốn chia sẻ.',
  close: 'Đóng',
  contactTitle: 'Nhận lộ trình xuất ngoại MIỄN PHÍ',
  contactIntro: 'Liên hệ StudyLink ngay để được chuyên gia tư vấn lộ trình xuất ngoại phù hợp với bạn.',
  hotline: 'Hotline 24/7',
  callNow: 'Gọi ngay',
  chatZalo: 'Nhắn Zalo',
  offices: 'Văn phòng tại Việt Nam',
  followUs: 'Theo dõi StudyLink',
};

const en = {
  appName: 'StudyLink',
  langToggle: 'Switch language',
  idLabel: 'ID',
  saved: 'Changes saved',
  saving: 'Saving…',
  saveError: 'Save failed — retry',
  home: 'Home',
  loading: 'Loading…',
  splashHint: 'Tap to continue',
  signOut: 'Sign out',
  provMajor: 'Major cities',
  provOther: 'Other provinces',
  serviceUpdating: 'The system is being updated. Please try again in a few minutes.',

  regHaveAccount: 'Already have a StudyLink account?',
  regLogin: 'Log in',
  regLoginHere: 'here',
  regTitle: 'Register',
  fullName: 'Full name',
  fullNamePh: 'Enter your full name',
  phone: 'Phone number',
  phonePh: '098 1234567',
  email: 'Email address',
  emailPh: 'email@example.com',
  yob: 'Year of birth',
  yobPh: 'e.g. 1998',
  channel: 'How did you hear about StudyLink?',
  channelSource: 'Source',
  referrerName: "Referrer's name",
  optional: 'Optional',
  event: 'Did you hear about us at an event?',
  eventNone: 'Not through an event',
  eventLocked: 'You registered through an event — your channel is already recorded.',
  residence: 'Where you live',
  dream: 'Your study-abroad dream',
  choose: 'Select',
  connect: 'Would you like StudyLink to connect with you?',
  yes: 'Yes',
  no: 'No',
  consent: 'By tapping “Start your adventure”, you agree that StudyLink may store and use your information to advise you on studying abroad. If you are under 18, please have a parent or guardian’s consent.',
  start: 'Start your adventure',
  checking: 'Checking…',
  connecting: 'Connecting…',
  errRequired: 'Please fill in all required fields.',
  errEmail: 'Please enter a valid email address.',
  errYob: 'Year of birth must be between 1980 and 2018.',
  errGeneric: 'Something went wrong. Please try again.',
  welcomeBack: 'Welcome back',
  welcomeBackActive: 'You already have an active enquiry with us. We’ll take you there so you can review and update your information.',
  welcomeBackNew: 'You’re already registered with us. A new enquiry will be created for you.',
  continue: 'Continue',
  createEnquiry: 'Create enquiry',
  cancel: 'Cancel',
  conflictTitle: 'We found several records',
  conflictHint: 'Pick your record. The others will be deactivated.',
  keepSelected: 'Keep selected record',

  hello: 'Hello there! 👋',
  hubLead1: 'Let’s begin your ',
  hubLeadHl: 'Study-Abroad Index',
  hubLead2: ' journey!',
  thanks1: ' thanks you for providing your contact details.',
  bubble1: 'Let’s see what your “portrait” reveals!',
  bubble2: 'Keep going! Just one more step to go.',
  bubble3: 'Which careers will suit you in the future? Let’s find out!',
  step1Title: 'YOUR PORTRAIT',
  step1Desc: 'Sketch your personal portrait.',
  step2Title: 'STUDY-ABROAD INDEX',
  step2Desc: 'Discover your study-abroad destiny.',
  step3Title: 'CAREER PREDICTION',
  step3Desc: 'Find the careers that fit you.',
  letsGo: "Let's Go",
  stepDone: 'Completed',
  gift1: 'Finish the journey to receive a ',
  giftHl: '"KU-TE"',
  gift2: ' gift from StudyLink! 🎁',
  comingSoon: 'This step is being finished. Please check back soon.',

  next: 'Continue',
  s1Title: 'YOUR PORTRAIT',
  parent: 'Parent',
  parentPick: 'Select: Mother / Father',
  mother: 'Mother',
  father: 'Father',
  parentName: 'Full name',
  parentPhone: 'Phone',
  parentEmail: 'Email',
  countries: 'Favourite countries',
  countriesHint: '(Tap to choose)',
  countriesCount: '{n}/3 countries selected',
  timeline: 'Planned time to go abroad',
  timelinePick: 'Select a time frame',
  socialTitle: 'Social media (optional)',
  socialPlatform: 'Platform',
  socialHandle: 'Username or link',
  socialNone: 'None',
  errParent: 'Please choose a parent.',
  errParentName: "Please enter the parent's full name.",
  errParentPhone: "Please enter the parent's phone number.",
  errParentEmail: "The parent's email looks invalid.",
  errCountries: 'Please choose at least 1 country.',
  saveFailed: 'Could not save. Please try again.',

  s2Title: 'VIEW YOUR INDEX',
  s2Sub1: 'Complete the ',
  s2SubB: '9 questions',
  s2Sub2: ' to calculate your index',
  calcIndex: 'Calculate my Study-Abroad Index',
  calculating: 'Calculating…',
  quizIncomplete: '{n} question(s) still unanswered.',
  questionOf: 'Question {n}/{total}',
  retakeGem: 'Retake the Index quiz',
  gemTitle: 'Your Study-Abroad Gem',
  step1First: 'Finish “Your portrait” first for a more accurate index.',
  goStep1: 'Go to Your portrait',

  s3Title: 'YOUR FUTURE CAREER',
  s3Sub1: 'Complete the ',
  s3SubB: '15 questions',
  s3Sub2: ' to calculate your profile',
  predict: 'Predict my career',
  retakeCareer: 'Retake the career quiz',
  finish: 'Finish',
  careerNeedsStep1: 'Please complete “Your portrait” (a parent’s details and a country) to unlock the final screen.',
  scoreLabel: 'Score',

  cheer1: 'Hoo…',
  congrats: 'Congratulations',
  unlocked: 'you have unlocked',
  unlockedTitle1: 'YOUR STUDY-ABROAD INDEX and',
  unlockedTitle2: 'CAREER PREDICTION',
  prize1: 'Your Study-Abroad Index map has been decoded! Along with your breakthrough roadmap, you get the chance to ride home a ',
  prizeHl: 'brand-new VinFast electric scooter',
  prize2: ' as a starting gift just for you.',
  shareBtn: 'Share your results with a StudyLink expert',
  roadmap: 'Get your FREE study-abroad roadmap',
  shareTitle1: 'Share your ',
  shareTitleHl: 'Study-Abroad Profile',
  shareTitle2: ' via:',
  shareText: 'Discover yourself and open the way to your future with StudyLink!',
  shareCopy: 'Copy link',
  shareCopied: 'Copied!',
  shareCopiedHint: 'Link copied — paste it into the app you want to share to.',
  close: 'Close',
  contactTitle: 'Get your FREE study-abroad roadmap',
  contactIntro: 'Contact StudyLink now and an expert will help you plan the study-abroad route that suits you.',
  hotline: '24/7 hotline',
  callNow: 'Call now',
  chatZalo: 'Chat on Zalo',
  offices: 'Offices in Vietnam',
  followUs: 'Follow StudyLink',
};

const copy = { vi, en };

export function wt(key, language = 'vi') {
  const lang = copy[language] || copy.vi;
  if (lang[key] !== undefined) return lang[key];
  if (copy.vi[key] !== undefined) return copy.vi[key];
  return key;
}
